export const FETCH_TICKETS = 'FETCH_TICKETS';
export const REQUEST_TICKETS = 'REQUEST_TICKETS';
export const REQUEST_TICKETS_SUCCESS = 'REQUEST_TICKETS_SUCCESS';
export const REQUEST_TICKETS_ERROR = 'REQUEST_TICKETS_ERROR';
